In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("Datasets/customer.csv")

In [3]:
data .head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [4]:
x = data.iloc[:,2:4]
y = data.iloc[:,-1]
y

0      No
1      No
2      No
3      No
4      No
5     Yes
6      No
7     Yes
8      No
9     Yes
10    Yes
11    Yes
12     No
13     No
14    Yes
15     No
16    Yes
17    Yes
18     No
19    Yes
20    Yes
21     No
22    Yes
23     No
24    Yes
25     No
26     No
27     No
28     No
29    Yes
30     No
31    Yes
32    Yes
33    Yes
34     No
35    Yes
36    Yes
37    Yes
38     No
39     No
40     No
41    Yes
42    Yes
43     No
44     No
45    Yes
46     No
47    Yes
48    Yes
49     No
Name: purchased, dtype: object

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3,random_state = 0)
print(x_train.shape,x_test.shape)

(35, 2) (15, 2)

## Ordinal Encoding on column Review and Education

In [6]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories = [["Poor","Average","Good"],["School","UG","PG"]])
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [7]:
x_train_trans = oe.transform(x_train)
x_test_trans = oe.transform(x_test)

In [8]:
x_train_trans = pd.DataFrame(x_train_trans,columns = x_train.columns)
x_test_trans = pd.DataFrame(x_test_trans,columns = x_test.columns)

In [9]:
x_train_trans

    review  education
0      0.0        0.0
1      0.0        2.0
2      0.0        2.0
3      2.0        1.0
4      1.0        1.0
5      0.0        1.0
6      1.0        1.0
7      1.0        1.0
8      0.0        1.0
9      2.0        2.0
10     1.0        0.0
11     0.0        2.0
12     1.0        1.0
13     1.0        0.0
14     2.0        0.0
15     1.0        0.0
16     0.0        1.0
17     2.0        0.0
18     2.0        1.0
19     0.0        1.0
20     0.0        0.0
21     1.0        2.0
22     1.0        2.0
23     2.0        0.0
24     2.0        0.0
25     2.0        1.0
26     1.0        2.0
27     0.0        2.0
28     2.0        1.0
29     0.0        2.0
30     0.0        2.0
31     2.0        2.0
32     1.0        0.0
33     2.0        2.0
34     1.0        1.0

In [10]:
x_test_trans

    review  education
0      0.0        0.0
1      2.0        1.0
2      2.0        1.0
3      2.0        2.0
4      2.0        2.0
5      0.0        2.0
6      2.0        0.0
7      0.0        0.0
8      0.0        2.0
9      1.0        1.0
10     2.0        2.0
11     0.0        0.0
12     0.0        2.0
13     1.0        0.0
14     2.0        0.0

In [11]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

## Label Encoding on Target column - Purchased

In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [13]:
le.fit(y_train)

LabelEncoder()

In [14]:
y_train_trans = le.transform(y_train)
y_test_trans = le.transform(y_test)

In [15]:
y_train_trans

array([1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0])

In [16]:
le.classes_

array(['No', 'Yes'], dtype=object)

## One Hot Encoding

In [17]:
df = pd.read_csv("Datasets/cars.csv")

In [18]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

### Using Pandas get_dummies() method

In [20]:
pd.get_dummies(df,columns = ["fuel","owner"],dtype = int)

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,0,1,0,0,1,0,0,0,0
1,Skoda,120000,370000,0,1,0,0,0,0,1,0,0
2,Honda,140000,158000,0,0,0,1,0,0,0,0,1
3,Hyundai,127000,225000,0,1,0,0,1,0,0,0,0
4,Maruti,120000,130000,0,0,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,0,1,1,0,0,0,0
8124,Hyundai,119000,135000,0,1,0,0,0,1,0,0,0
8125,Maruti,120000,382000,0,1,0,0,1,0,0,0,0
8126,Tata,25000,290000,0,1,0,0,1,0,0,0,0
8127,Tata,25000,290000,0,1,0,0,1,0,0,0,0

### K-1 One hot Encoding

In [21]:
pd.get_dummies(df,columns = ["fuel","owner"],dtype = int,drop_first = True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,1,0,0,0,0,0,0
1,Skoda,120000,370000,1,0,0,0,1,0,0
2,Honda,140000,158000,0,0,1,0,0,0,1
3,Hyundai,127000,225000,1,0,0,0,0,0,0
4,Maruti,120000,130000,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,1,0,0,0,0
8124,Hyundai,119000,135000,1,0,0,1,0,0,0
8125,Maruti,120000,382000,1,0,0,0,0,0,0
8126,Tata,25000,290000,1,0,0,0,0,0,0
8127,Tata,25000,290000,1,0,0,0,0,0,0

#### “The problem with get_dummies() is that it doesn’t store the mapping or order of categories. This can lead to inconsistent columns between training and testing data. That’s why in production we often use sklearn.preprocessing.OneHotEncoder instead, which remembers the categories.”

### One Hot Encoding using sklearn

In [46]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [47]:
df['owner'].nunique()

5

In [24]:
x = df.iloc[:,0:4]
y = df.iloc[:,-1]
print(x.shape,y.shape)

(8128, 4) (8128,)

In [25]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 0)

In [27]:
x_train.head()

         brand  km_driven    fuel         owner
3042   Hyundai      60000     LPG   First Owner
1520      Tata     150000  Diesel   Third Owner
2611   Hyundai     110000  Diesel  Second Owner
3544  Mahindra      28000  Diesel  Second Owner
4138    Maruti      15000  Petrol   First Owner

In [28]:
y_train.head()

3042     375000
1520     150000
2611     459999
3544    1050000
4138     700000
Name: selling_price, dtype: int64

In [29]:
from sklearn.preprocessing import OneHotEncoder

In [37]:
ohe = OneHotEncoder(drop = 'first',dtype = 'int32', sparse_output=False)

In [38]:
x_train_trans = ohe.fit_transform(x_train[['fuel','owner']])
x_test_trans = ohe.transform(x_test[['fuel','owner']])

In [39]:
x_train_trans.shape

(6502, 7)

In [40]:
x_train_trans

array([[0, 1, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 1, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]], dtype=int32)

In [44]:
new_data = np.hstack((x_train[['brand','km_driven']].values,x_train_trans)) # Join 2 arrays horizontally

In [45]:
new_data = pd.DataFrame(new_data)
new_data

               0       1  2  3  4  5  6  7  8
0        Hyundai   60000  0  1  0  0  0  0  0
1           Tata  150000  1  0  0  0  0  0  1
2        Hyundai  110000  1  0  0  0  1  0  0
3       Mahindra   28000  1  0  0  0  1  0  0
4         Maruti   15000  0  0  1  0  0  0  0
...          ...     ... .. .. .. .. .. .. ..
6497        Tata   70000  1  0  0  0  0  0  1
6498        Ford  100000  1  0  0  0  1  0  0
6499     Hyundai   90000  0  0  1  0  1  0  0
6500  Volkswagen   90000  1  0  0  0  0  0  0
6501     Hyundai  110000  0  0  1  0  0  0  0

[6502 rows x 9 columns]

### One hot encoding on Brand Column (32 Categories)

In [48]:
counts = df['brand'].value_counts()
counts

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [49]:
threshold = 100

In [52]:
repl = counts[counts <= threshold].index
repl

Index(['Nissan', 'Jaguar', 'Volvo', 'Datsun', 'Mercedes-Benz', 'Fiat', 'Audi',
       'Lexus', 'Jeep', 'Mitsubishi', 'Land', 'Force', 'Isuzu', 'Ambassador',
       'Kia', 'MG', 'Daewoo', 'Ashok', 'Opel', 'Peugeot'],
      dtype='object', name='brand')

In [55]:
pd.get_dummies(df['brand'].replace(repl,"Uncommon"),dtype = int).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Uncommon,Volkswagen
7220,0,0,0,0,0,0,1,0,0,0,0,0,0
6169,0,0,0,0,0,0,0,0,0,1,0,0,0
4562,0,0,1,0,0,0,0,0,0,0,0,0,0
3948,0,0,0,0,0,0,1,0,0,0,0,0,0
7887,0,0,0,0,0,0,0,0,0,1,0,0,0